export const SUBSCRIPTION_PLANS = {
  monthly: {
    name: "Monthly",
    price: "$10",
    priceAmount: 10,
    interval: "month",
    description: "2 weeks free trial!",
    price_id: "price_1T0ooo9JNqgx0F3SwivBtcQg",
    product_id: "prod_TymNB3X9S7N3Ni",
    trial: true,
    badge: "Most Popular",
  },
  bimonthly: {
    name: "Bimonthly",
    price: "$5",
    priceAmount: 5,
    interval: "2 months",
    description: "Save 50% compared to monthly",
    price_id: "price_1T0opM9JNqgx0F3S6CWWgVMA",
    product_id: "prod_TymOcxiZj8ZPiM",
    trial: false,
    badge: null,
  },
  yearly: {
    name: "Yearly",
    price: "$3",
    priceAmount: 3,
    interval: "year",
    description: "Best price — save 97%!",
    price_id: "price_1T0opk9JNqgx0F3Scv8O6b1O",
    product_id: "prod_TymOb2qlxLiiVP",
    trial: false,
    badge: "Best Value",
  },
} as const;
