export const SUBSCRIPTION_PLANS = {
  monthly: {
    name: "Mujor",
    price: "$10",
    priceAmount: 10,
    interval: "muaj",
    description: "2 javë provë falas!",
    price_id: "price_1T0ooo9JNqgx0F3SwivBtcQg",
    product_id: "prod_TymNB3X9S7N3Ni",
    trial: true,
    badge: "Më Popullar",
  },
  bimonthly: {
    name: "2-Mujor",
    price: "$5",
    priceAmount: 5,
    interval: "2 muaj",
    description: "Kurse 50% krahasuar me mujor",
    price_id: "price_1T0opM9JNqgx0F3S6CWWgVMA",
    product_id: "prod_TymOcxiZj8ZPiM",
    trial: false,
    badge: null,
  },
  yearly: {
    name: "Vjetor",
    price: "$3",
    priceAmount: 3,
    interval: "vit",
    description: "Çmimi më i mirë - kurse 97%!",
    price_id: "price_1T0opk9JNqgx0F3Scv8O6b1O",
    product_id: "prod_TymOb2qlxLiiVP",
    trial: false,
    badge: "Më i Mirë",
  },
} as const;
